export const CONTRACT_LOAD = "CONTRACT_LOAD";
export const CONTRACT_ADD = "CONTRACT_ADD";
export const CONTRACT_REMOVE = "CONTRACT_REMOVE";
export const CONTRACT_SELECT = "CONTRACT_SELECT";
export const CONTRACT_DESELECT = "CONTRACT_DESELECT";
export const CONTRACT_REGISTER = "CONTRACT_REGISTER";